In [1]:
# shift + tab : import 함수 도움말 웹창 띄우기


In [2]:
a = [1,2,3]
b = a * 2
b

[1, 2, 3, 1, 2, 3]

In [4]:
a =[1,2,3]
b = []
for x in a:
    b.append(x * 2)
b

[2, 4, 6]

In [5]:
c = [x * 2 for x in a]
c

[2, 4, 6]

In [1]:
import numpy as np

In [2]:
ar0 = np.array([1,2,3])
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
print([1,2,3])
print()
print(ar0)
print()
print(ar1)
print()
print(ar2)

[1, 2, 3]

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
ar2   # 콤마도 생기고 형식인 array도 출력됨

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
ar3 = np.array([[1,2,3],[4,5,6],[7,8]])

In [6]:
ar3

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [7]:
ar4 = np.array([1, 2, 3.5]) #같은 타입이여야 함

In [8]:
ar4

array([1. , 2. , 3.5])

In [9]:
ar5 = np.array([1,2,'a'])  #같은 타입이여야 함

In [10]:
ar5

array(['1', '2', 'a'], dtype='<U11')

In [11]:
ar0 = np.array([1, 2, 3]) 
ar1 = np.array([1, 2, 3], dtype = 'int8') 

In [13]:
ar0.dtype 

dtype('int32')

In [14]:
ar2 = ar0.astype('float32')
ar2

array([1., 2., 3.], dtype=float32)

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.ones(4)((2, 3))

array([0., 0., 0., 0.])

In [17]:
np.zeros(4, dtype = 'i')

array([0, 0, 0, 0], dtype=int32)

In [18]:
np.ones((2, 3), dtype = 'i')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [19]:
np.linspace(0, 15, 4) # 시작 끝 포함

array([ 0.,  5., 10., 15.])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.arange(10) # 끝 포함 안됨, 실수 사용가능

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1.5, 5)

array([1.5, 2.5, 3.5, 4.5])

In [23]:
np.arange(2, 4.5, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4])

In [25]:
np.linspace??   #도움말 볼수 있는 방법중 하나

In [26]:
np.random.random((2, 4))

array([[0.91395532, 0.73584765, 0.5636203 , 0.98303662],
       [0.8065315 , 0.7324129 , 0.12199488, 0.15098103]])

In [27]:
np.random.uniform(3.5, 4, (3, 3))   # 넘파이 uniform 끝 포함 안됨

array([[3.90641665, 3.69900944, 3.6091899 ],
       [3.96932434, 3.89841489, 3.61670525],
       [3.90250688, 3.50973682, 3.7207753 ]])

In [28]:
np.random.randint(0, 7, (2, 3, 4))   # 넘파이 randint 끝 포함 안됨

array([[[1, 4, 5, 1],
        [0, 5, 5, 2],
        [0, 6, 4, 3]],

       [[1, 4, 1, 0],
        [5, 1, 5, 0],
        [1, 5, 1, 4]]])

In [29]:
np.random.randint(-5, 5, 7)   # 넘파이 randint 끝 포함 안됨

array([-5,  2, -5, -1,  0,  2, -5])

In [30]:
ar0 = np.array([1, 2, 3]) 
ar1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
ar2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 

In [31]:
print('차원:', ar0.ndim, '\t크기', ar0.shape)    # 가져온 데이터의 상태를 파악
print('차원:', ar1.ndim, '\t크기', ar1.shape) 
print('차원:', ar2.ndim, '\t크기', ar2.shape)

차원: 1 	크기 (3,)
차원: 2 	크기 (3, 3)
차원: 3 	크기 (2, 2, 2)


In [32]:
ar0 = np.arange(12) 
ar0 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
ar0.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
ar0.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [34]:
np.reshape(ar0, (4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
ar1 = ar0.reshape(2, 2, 3) 
ar1 

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
ar1.ravel()   # np.ravel(ar), ar.flatten() 다 동일

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
np.ravel(ar1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
ar1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
ar = np.arange(8).reshape((4, 2))
ar

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
ar.T 

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [43]:
np.transpose(ar) 

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [46]:
np.swapaxes(ar, 0, 1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [47]:
ar = np.arange(12).reshape(2, 2, 3) 
ar 

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
ar[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
ar[0][1] 

array([3, 4, 5])

In [51]:
ar[0, 1] 

array([3, 4, 5])

In [50]:
ar[0, 1, 2]

5

In [52]:
ar = np.arange(20).reshape(4,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
ar[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
ar[2:,:0]

array([], shape=(2, 0), dtype=int32)

In [58]:
ar[2:][:0]

array([], shape=(0, 5), dtype=int32)

In [54]:
ar[2:, :-2] # 행번호[열번호]

array([[10, 11, 12],
       [15, 16, 17]])

In [55]:
ar[2:][:-2] # 행번호[행번호]

array([], shape=(0, 5), dtype=int32)

In [56]:
ar[::-1, ::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [59]:
ar[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
ar[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [62]:
ar[:2,3:]

array([[3, 4],
       [8, 9]])

In [63]:
ar[::,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [64]:
ar[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [65]:
ar[-1::-2,-3::-2]

array([[17, 15],
       [ 7,  5]])

In [66]:
ar[[0,1]]   # list은 써서 해도 되는데 튜플은 다르게 나옴

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
ar[(0,1)]

1

In [67]:
ar[2:, [1,3,4]]

array([[11, 13, 14],
       [16, 18, 19]])

In [68]:
ar[[0,2], [2,4]]

array([ 2, 14])

In [71]:
ar = np.arange(40).reshape(5,8)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [72]:
ar[[0,3,4],[1,2,6]]

array([ 1, 26, 38])

In [73]:
ar[(0,3,4),(1,2,6)]   # 이 때는 튜플로 해도 리스트랑 같은 값이 나옴

array([ 1, 26, 38])

In [74]:
ar[[1,2]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [75]:
ar[(1,2)]

10

In [76]:
ar[[0,2,3]][:, [1,3,4,5]]

array([[ 1,  3,  4,  5],
       [17, 19, 20, 21],
       [25, 27, 28, 29]])

In [77]:
ar * 2

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58, 60, 62],
       [64, 66, 68, 70, 72, 74, 76, 78]])