In [11]:
import pandas as pd
import numpy as np
names1 = np.array(['둘리', '호이', '영미', '길동', '또치', '마이클'])
score1 = np.array([84, 21, 87, 100, 59, 46]) 
names2 = np.array(['또치', '둘리', '길동', '영미', '마이클', '호이']) 
score2 = np.array([99, 87, 87, 84, 77, 15]) 
s1 = pd.Series(score1, index = names1) 
s2 = pd.Series(score2, index = names2)

In [12]:
np.append(score1, 23) 

array([ 84,  21,  87, 100,  59,  46,  23])

In [13]:
np.insert(score1, 3, 77)

array([ 84,  21,  87,  77, 100,  59,  46])

In [14]:
np.delete(score1, 3)

array([84, 21, 87, 59, 46])

In [15]:
s1[1] = 77           # 수정

In [16]:
s1['슬기'] = 99     # 추가

In [18]:
s1

둘리      84
호이      77
영미      87
길동     100
또치      59
마이클     46
슬기      99
dtype: int64

In [45]:
del s1['길동']      # 추가 삭제는 꼭 index명, 수정은 index번호도 가능

In [19]:
s1.loc[9] = 7

In [20]:
s1

둘리      84
호이      77
영미      87
길동     100
또치      59
마이클     46
슬기      99
9        7
dtype: int64

In [53]:
import pandas as pd
import numpy as np
names1 = np.array(['둘리', '호이', '영미', '길동', '또치', '마이클'])
score1 = np.array([84, 21, 87, 100, 59, 46]) 
names2 = np.array(['또치', '둘리', '길동', '영미', '마이클', '호이']) 
score2 = np.array([99, 87, 87, 84, 77, 15]) 
s1 = pd.Series(score1, index = names1) 
s2 = pd.Series(score2, index = names2)

In [37]:
score1 < 30

array([False,  True, False, False, False, False])

In [38]:
score1[score1 < 30]

array([21])

In [40]:
score2[score1 < 30]     #  배열이라서 바로 그 위치에 있는 값이 나옴

array([87])

In [33]:
s1 < 30

둘리     False
호이      True
영미     False
길동     False
또치     False
마이클    False
dtype: bool

In [34]:
s1[s1 < 30]

호이    21
dtype: int32

In [35]:
s2[s1 < 30]       # 정렬되어 있지 않더라도 인덱스을 기준으로 색인함

호이    15
dtype: int32

In [41]:
s1

둘리      84
호이      21
영미      87
길동     100
또치      59
마이클     46
dtype: int32

In [42]:
s2

또치     99
둘리     87
길동     87
영미     84
마이클    77
호이     15
dtype: int32

In [43]:
s2[s1.index]

둘리     87
호이     15
영미     84
길동     87
또치     99
마이클    77
dtype: int32

In [44]:
s2 = s2[s1.index]   # 원본파일 저장

In [62]:
import pandas as pd
import numpy as np
n1 = input('이름을 입력하세요:').split(' ')
names1 = np.array(n1)
n2 = input('과목을 입력하세요:').split(' ')
names2 = np.array(n2)
math = input('%d 성적을 입력하세요:' % names2[0]).split(' ')
math = [int (i) for i in math]
score1 = np.array(math)
eng = input('%d 성적을 입력하세요:' % names2[1]).split(' ')
eng = [int (i) for i in eng]
score2 = np.array(eng) 

이름을 입력하세요:길동 미나 슬기
과목을 입력하세요:수학 영어
수학성적을 입력하세요:100 70 35
영어성적을 입력하세요:77 11 56


In [67]:
# 내가 하다가 시간관계상 다 못한거 꼭 마무리 지을것
import pandas as pd
import numpy as np
n1 = input('이름을 입력하세요:').split(' ')
names1 = np.array(n1)
n2 = input('과목을 입력하세요:').split(' ')
names2 = np.array(n2)
num = 0
while num <= len(n2)
    if num == 0
        subject[num] = input('%d 성적을 입력하세요:' % names2[num]).split(' ')
        subject[num] = [int (i) for i in subject[num]]
        score1 = np.array(subject[num])
    num += 1

SyntaxError: invalid syntax (<ipython-input-67-f770065ad991>, line 8)

In [63]:
n1

['길동', '미나', '슬기']

In [65]:
s1 = pd.Series(score1, index = names1) 
s2 = pd.Series(score2, index = names1)

In [64]:
score1

array([100,  70,  35])

In [75]:
names = input('이름: ').split()
subjects = input('과목: ').split()

print('입력된 이름:', names) # 테스트
print('입력된 과목:', subjects) # 테스트

이름: 길동 미나 슬기
과목: 수학 영어
입력된 이름: ['길동', '미나', '슬기']
입력된 과목: ['수학', '영어']


In [76]:
listOfScores = []
for subject in subjects:
    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()
    print('입력된', subject + '의 성적:', scores) # 테스트
    scores = list(map(int, scores))
    print(scores)      # 테스트
    listOfScores.append(pd.Series(scores, index = names))
    listOfScores[-1].name = subject
    
for scores in listOfScores:
    print(scores)


길동 미나 슬기의 수학 성적: 100 70 35
입력된 수학의 성적: ['100', '70', '35']
[100, 70, 35]

길동 미나 슬기의 영어 성적: 77 11 56
입력된 영어의 성적: ['77', '11', '56']
[77, 11, 56]
길동    100
미나     70
슬기     35
Name: 수학, dtype: int64
길동    77
미나    11
슬기    56
Name: 영어, dtype: int64


In [77]:
listOfScores = {}                                                 # 이부분 달라짐 딕셔너리
for subject in subjects:
    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()
    print('입력된', subject + '의 성적:', scores) # 테스트
    scores = [int(x) for x in scores]                           # 이부분 달라짐  for사용 위에는 map사용
    print(scores)     # 테스트
    listOfScores[subject] = pd.Series(scores, index = names)     # 이부분 달라짐
    listOfScores[subject].name = subject
    
for subject in listOfScores:                                    # 이부분 달라짐
    print(subject, listOfScores[subject])                        # 이부분 달라짐


길동 미나 슬기의 수학 성적: 100 70 35
입력된 수학의 성적: ['100', '70', '35']
[100, 70, 35]

길동 미나 슬기의 영어 성적: 77 11 56
입력된 영어의 성적: ['77', '11', '56']
[77, 11, 56]
수학 길동    100
미나     70
슬기     35
Name: 수학, dtype: int64
영어 길동    77
미나    11
슬기    56
Name: 영어, dtype: int64


In [82]:
listOfScores = {}
scoreSum = pd.Series([0] * len(names), index = names)
for subject in subjects:
    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()
    print('입력된', subject + '의 성적:', scores) # 테스트

    print(scores)     # 테스트
    listOfScores[subject] = pd.Series(scores, index = names)
    listOfScores[subject].name = subject    
    listOfScores[subject] = listOfScores[subject].astype('int')   # 이부분 달라짐
    scoreSum += listOfScores[subject]
    
    listOfScores[subject]['합'] = listOfScores[subject].sum()
    
for subject in listOfScores:                                    
    print(subject, listOfScores[subject])
    
print('합', scoreSum)


길동 미나 슬기의 수학 성적: 100 70 35
입력된 수학의 성적: ['100', '70', '35']
['100', '70', '35']

길동 미나 슬기의 영어 성적: 77 11 56
입력된 영어의 성적: ['77', '11', '56']
['77', '11', '56']
수학 길동    100
미나     70
슬기     35
합     205
Name: 수학, dtype: int64
영어 길동     77
미나     11
슬기     56
합     144
Name: 영어, dtype: int64
합 길동    177
미나     81
슬기     91
dtype: int64


In [83]:
from functools import reduce
reduce(lambda x, y: x + y, listOfScores.values())

길동    177
미나     81
슬기     91
합     349
dtype: int64

In [84]:
# Series = 1차원배열
# DataFrame = 2차원배열 + index + colume

names1 = np.array(['둘리', '호이', '영미', '길동', '또치', '마이클'])
score1 = np.array([84, 21, 87, 100, 59, 46]) 
names2 = np.array(['또치', '둘리', '길동', '영미', '마이클', '호이']) 
score2 = np.array([99, 87, 87, 84, 77, 15]) 
s1 = pd.Series(score1, index = names1) 
s2 = pd.Series(score2, index = names2)

In [85]:
d0 = pd.DataFrame()          # 인덱스에 맞춰서 값을 가져옴
d0['수학'] = s1              # s1대신 score1로 해보기
d0['국어'] = s2              # s2대신 score2로 해보기
d0

수학  국어
둘리    84  87
호이    21  15
영미    87  84
길동   100  87
또치    59  99
마이클   46  77

In [86]:
d1 = pd.DataFrame()         # 인덱스 부분이 없어서 그냥 순서대로 매칭해서 값 가져옴
d1['수학'] = score1
d1['국어'] = score2
d1                       

수학  국어
0   84  99
1   21  87
2   87  87
3  100  84
4   59  77
5   46  15

In [110]:
# 원표시 또는 역슬래시 넣고 엔터치고 밑에 쓰면 한줄로 인식함(단, 빈칸이나 주석이 \뒤에 있음 안됨)

scores = np.array([84,87,78,21,15,84,87,84,76,100,87,99,\
                   59,99,59,46,77,56]).reshape(6,3)
scores

array([[ 84,  87,  78],
       [ 21,  15,  84],
       [ 87,  84,  76],
       [100,  87,  99],
       [ 59,  99,  59],
       [ 46,  77,  56]])

In [111]:
d2 = pd.DataFrame(scores)
d2

0   1   2
0   84  87  78
1   21  15  84
2   87  84  76
3  100  87  99
4   59  99  59
5   46  77  56

In [112]:
names = ['둘리', '호이', '영미', '길동', '또치', '마이클']
lectures = ['수학', '국어', '영어']

In [113]:
d3 = pd.DataFrame(scores, index = names, columns = lectures)
d3

수학  국어  영어
둘리    84  87  78
호이    21  15  84
영미    87  84  76
길동   100  87  99
또치    59  99  59
마이클   46  77  56

In [114]:
scoresWithLectures = {'수학': [84, 21, 87, 100, 59, 46], \
                     '국어': [87, 84, 76, 100, 87, 99], \
                     '영어': [59,99,59,46,77,56]}

In [115]:
d4 = pd.DataFrame(scoresWithLectures, index = names)
d4

수학   국어  영어
둘리    84   87  59
호이    21   84  99
영미    87   76  59
길동   100  100  46
또치    59   87  77
마이클   46   99  56

In [7]:
import pandas as pd
import numpy as np
names = input('이름: ').split()
subjects = input('과목: ').split()

print('입력된 이름:', names) # 테스트
print('입력된 과목:', subjects) # 테스트

'''listOfScores = pd.DataFrame(index = names)
for subject in subjects:
    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()
    listOfScores[subject] = list(map(int, scores))
listOfScores'''

이름: 철수 영희 슬기
과목: 수학 과학
입력된 이름: ['철수', '영희', '슬기']
입력된 과목: ['수학', '과학']


"listOfScores = pd.DataFrame(index = names)\nfor subject in subjects:\n    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()\n    listOfScores[subject] = list(map(int, scores))\nlistOfScores"

In [8]:
listOfScores = []
for subject in subjects:
    scores = input('\n'+' '.join(names) + '의 ' + subject + ' 성적: ').split()
    listOfScores.append(list(map(int, scores)))
listOfScores


철수 영희 슬기의 수학 성적: 100 90 80

철수 영희 슬기의 과학 성적: 40 50 60


[[100, 90, 80], [40, 50, 60]]

In [9]:
pd.DataFrame(np.array(listOfScores).T, index = names, columns = subjects)

수학  과학
철수  100  40
영희   90  50
슬기   80  60